### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by zjin-lcf** [ROCmSoftwarePlatform/hipFFT#18]
Could you please clarify if users still need to clone rocFFT after 'git submodule update --init' 

git clone https://github.com/ROCmSoftwarePlatform/hipFFT.git
cd hipFFT
git submodule update --init
mkdir build
cd build
cmake  -DCMAKE_CXX_COMPILER=hipcc -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENTS=ON -L ..

CMake Error at cmake/dependencies.cmake:51 (find_package):
  By not providing "Findrocfft.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "rocfft", but
  CMake did not find one.

  Could not find a package configuration file provided by "rocfft" with any
  of the following names:

    rocfftConfig.cmake
    rocfft-config.cmake

  Add the installation prefix of "rocfft" to CMAKE_PREFIX_PATH or set
  "rocfft_DIR" to a directory containing one of the above files.  If "rocfft"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:123 (include)

**Comment by evetsso** [comment]
hipFFT interacts with the rocFFT in two ways.  The first is that, as you've discovered, the hipFFT git repository has rocFFT as a submodule.  This is so that some utility and testing code can be shared between the two.

The other interaction is that building hipFFT requires an installed backend library that knows how to actually perform FFTs.  hipFFT itself is just a wrapper around those backend libraries.  rocFFT is the default backend library, though it's also possible to use cuFFT.

Your CMake error is because it can't find a backend library.  The build process does not care whether you build rocFFT yourself or get it from a package.  If you do want to build rocFFT from source, you will most likely want to make a separate clone.  The submodule in hipFFT will not have all of the latest changes.

But installing a rocFFT package is easier, if you're able to use one.   Either way, once you have the library you would need to do as the CMake error suggests and ensure that CMake will find the library in its module/prefix paths.

I'm closing this issue as I believe that answers your question.  Please reopen the issue if you have further questions on this topic.
